name: Pylint

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
        FPD_FLICKR_API_KEY: ${{ secrets.FLICKR_API_KEY }}
        FPD_FLICKR_API_SECRET: ${{ secrets.FLICKR_API_SECRET }}
      env:
        FPD_FLICKR_API_KEY: ${{ secrets.FLICKR_API_KEY }}
        FPD_FLICKR_API_SECRET: ${{ secrets.FLICKR_API_SECRET }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Analysing the code with pylint
      run: |
        python -m pylint --fail-under=10 `find -regextype egrep -regex '(.*.py)$'` |
        tee pylint.txt
    - name: Upload pylint.txt as artifact
      uses: actions/upload-artifact@v2
      with:
        name: pylint report
        path: pylint.txt